### PR TITLE
python3 support

### PR DESCRIPTION
**Pull request by orisano**

### CODE REVIEW

**Comment by entone** [comment]
Hi @orisano I haven't used this library in over 2 years. Thank you so much for the pull request, would you like to become the maintainer?

**Comment by orisano** [comment]
thank you @entone. I can't read and write english well. however i challenge a maintainer.

**Comment by entone** [comment]
@orisano please merge this PR if it passes all the tests

**Comment by orisano** [comment]
I want to stop supporting python2

**Comment by entone** [comment]
Ok, make sure to write a full test suite for python 3

**Comment by orisano** [comment]
Thank you @entone !

**Comment by orisano** [comment]
please see #17 .

**Pull request closed without merging**
